name: Schedule API Call for Overdue Items

on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  send-overdue-email:
    runs-on: ubuntu-latest
    steps:
      - name: Call API to Send Overdue Email
        run: curl -X POST "https://borrowers-slip.vercel.app/api/check-overdue"
